### ISSUE TITLE
Add heterozygous rate option.

### ISSUE THREAD

**Issue by xiekunwhy** [felixfan/GenTools#1]
Hi,
Would you please add a heterozygous ratio option to filter out those sites with  heterozygous ratio larger than a given value. As we found many snp with very high het ratio because of wrong mapping.

Best wishes,
Kun

**Comment by felixfan** [comment]
you can use --het first, then use --remove-inds

**Comment by xiekunwhy** [comment]
Hi,
I think you didn't understand what I means exactly.
I means snp sites het rate(for bi-allelic site, het_rate = (number of 0/1)/(all typed inds), for example, there are 200 inds in a vcf file, for chr1pos1000, all 200 inds are typed and 150 of them are 0/1, the het rate of chr1pos1000 is 150/200), not inds het rate.
Best wishes,
Kun
